# Generated by Django 4.1 on 2023-07-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UITheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("about_me", models.TextField(null=True)),
                ("displayed_username", models.CharField(max_length=100, null=True)),
                ("display_fullname", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("photo", models.ImageField(upload_to="photos/")),
                ("sex", models.CharField(max_length=1, null=True)),
                ("born_on", models.DateField(null=True)),
                ("prefered_theme", models.IntegerField(default=0)),
                ("prefered_section", models.IntegerField(default=0)),
                ("default_discussions_ordering", models.IntegerField(default=1)),
                ("default_comments_ordering", models.IntegerField(default=1)),
                ("default_user_comments_ordering", models.IntegerField(default=1)),
                (
                    "ui_theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_set",
                        to="users.uitheme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_context_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("domain", models.CharField(max_length=60, null=True)),
                ("description", models.CharField(max_length=240, null=True)),
                ("number", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_context_set",
                        to="users.usercontext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSectionDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=60, null=True)),
                ("description", models.CharField(max_length=240, null=True)),
                (
                    "userSection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_section_set",
                        to="users.usersection",
                    ),
                ),
            ],
        ),
    ]
