# Generated by Django 4.1 on 2023-07-04 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_remove_usercontext_active_remove_usercontext_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="rows_per_page",
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("about_me", models.TextField(null=True)),
                ("displayed_username", models.CharField(max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("photo", models.ImageField(upload_to="photos/")),
                ("sex", models.CharField(max_length=1, null=True)),
                ("born_on", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_detail_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
