# Generated by Django 4.1 on 2023-07-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usercontext_rows_per_page_userdetail"),
    ]

    operations = [
        migrations.RemoveField(model_name="usercontext", name="about_me",),
        migrations.RemoveField(model_name="usercontext", name="born_on",),
        migrations.RemoveField(model_name="usercontext", name="displayed_username",),
        migrations.RemoveField(model_name="usercontext", name="first_name",),
        migrations.RemoveField(model_name="usercontext", name="last_name",),
        migrations.RemoveField(model_name="usercontext", name="photo",),
        migrations.RemoveField(model_name="usercontext", name="sex",),
    ]
