# Generated by Django 4.1 on 2023-07-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersectiondomain_section_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="usersection", name="domain",),
    ]
