# Generated by Django 4.1 on 2023-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_usersection_domain"),
    ]

    operations = [
        migrations.RemoveField(model_name="usersection", name="active",),
        migrations.AddField(
            model_name="usersection",
            name="type",
            field=models.CharField(default="P", max_length=1),
        ),
    ]
