# Generated by Django 4.1 on 2023-07-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_usersection_active_usersection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="notify_on_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="notify_on_discussion",
            field=models.BooleanField(default=False),
        ),
    ]
