# Generated by Django 4.1 on 2023-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_usercontext_notify_on_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
