# Generated by Django 4.1 on 2023-08-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_usercontext_ui_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersection",
            name="title",
            field=models.CharField(max_length=160, null=True),
        ),
    ]
