# Generated by Django 4.1 on 2024-02-23 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_remove_usercontext_ui_theme_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="UITheme",),
        migrations.RenameField(
            model_name="usercontext",
            old_name="prefered_section",
            new_name="default_theme",
        ),
        migrations.RemoveField(model_name="usercontext", name="prefered_theme",),
        migrations.AddField(
            model_name="usercontext",
            name="auto_show_all_replies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="display_time_difference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="notify_on_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="favorite",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersection",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersection",
            name="title",
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="usercontext",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_context_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_detail_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usersection",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_section_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
