# Generated by Django 4.1 on 2023-08-14 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0012_usersection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersection",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_section_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
