# Generated by Django 4.1 on 2023-08-14 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_alter_usersection_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_detail_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
