# Generated by Django 4.1 on 2023-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_usercontext_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
