# Generated by Django 4.1 on 2023-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_usercontext_ip_address"),
    ]

    operations = [
        migrations.DeleteModel(name="UITheme",),
        migrations.RemoveField(model_name="usercontext", name="prefered_section",),
        migrations.RemoveField(model_name="usercontext", name="prefered_theme",),
        migrations.AddField(
            model_name="usercontext",
            name="display_time_difference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="notify_on_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersection",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
