# Generated by Django 4.1 on 2023-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_delete_uitheme_remove_usercontext_prefered_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="default_theme",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
