# Generated by Django 4.1 on 2023-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_usercontext_default_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontext",
            name="default_theme",
            field=models.IntegerField(null=True),
        ),
    ]
