# Generated by Django 4.1 on 2023-08-15 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0020_alter_usercontext_default_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="favorite",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="usercontext",
            name="default_theme",
            field=models.IntegerField(default=0),
        ),
    ]
