# Generated by Django 4.1 on 2023-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_userdetail_favorite_alter_usercontext_default_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
