# Generated by Django 4.1 on 2023-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_userdetail_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="auto_show_all_replies",
            field=models.BooleanField(default=False),
        ),
    ]
