# Generated by Django 4.1 on 2023-09-04 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0023_usercontext_auto_show_all_replies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="favorite",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
