# Generated by Django 4.1 on 2023-07-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleuserquery", old_name="title", new_name="key_word",
        ),
        migrations.RemoveField(model_name="articleuserquery", name="url",),
        migrations.AddField(
            model_name="articleuserquery",
            name="days_old",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="articleuserquery",
            name="section",
            field=models.IntegerField(null=True),
        ),
    ]
