# Generated by Django 4.1 on 2023-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_rename_title_articleuserquery_key_word_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="article", name="published_on", field=models.DateTimeField(),
        ),
    ]
