# Generated by Django 4.1 on 2023-07-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_discussion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="commnet_count",
            field=models.IntegerField(default=0),
        ),
    ]
