# Generated by Django 4.1 on 2023-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_rename_commnet_count_article_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scrapping",
            field=models.BooleanField(default=False),
        ),
    ]
