# Generated by Django 4.1 on 2023-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_scrapping"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="scrapping",),
    ]
