version: "3.3"

services:
  db:
    image:  postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=diskuze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py makemigrations && python manage.py migrate && gunicorn 0.0.0.0:8000 diskuze.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=diskuze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

