version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ../postgres/db:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # Přidáváme init.sql
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=noncensuradb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - diskuze_network  # Přidejte, pokud používáte vlastní síť
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: bash -c "while ! python -c 'import psycopg2; conn = psycopg2.connect(host=\"db\", port=5432, user=\"postgres\", password=\"postgres\", dbname=\"noncensuradb\"); conn.close()' > /dev/null 2>&1; do sleep 1; done && echo yes | python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../media/photos:/noncensura/media/photos
    environment:
      - DJANGO_SETTINGS_MODULE=diskuze.settings
    networks:
      - diskuze_network  # Přidejte, pokud používáte vlastní síť
    depends_on:
      - db

  #nginx:
  #  image: nginx:latest
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Přidáváme konfiguraci pro proxy_pass na Django aplikaci
  #    - ./certs/localhost.pem:/etc/nginx/certs/localhost.pem
  #    - ./certs/localhost-key.pem:/etc/nginx/certs/localhost-key.pem
   #   - ./nginx/cert.crt:/etc/nginx/cert.crt  # Certifikát pro HTTPS
   #   - ./nginx/cert.key:/etc/nginx/cert.key  # Soukromý klíč pro HTTPS
   # ports:
   #   - "80:80"
   #   - "443:443"  # Přidáváme port pro HTTPS
   # networks:
   #   - diskuze_network
   # depends_on:
   #    - web

networks:
  diskuze_network:  # Přidejte, pokud používáte vlastní síť
    driver: bridge  # Přidejte, pokud používáte vlastní síť

