# Generated by Django 4.1 on 2023-06-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0003_usercontext_default_section"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="section_number",),
        migrations.AlterField(
            model_name="discussion",
            name="description",
            field=models.CharField(max_length=320, null=True),
        ),
    ]
