# Generated by Django 4.1 on 2023-06-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0005_alter_discussion_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercontext", old_name="is_active", new_name="active",
        ),
        migrations.RenameField(
            model_name="usercontext", old_name="is_staff", new_name="staff",
        ),
        migrations.AddField(
            model_name="section",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(name="Article",),
    ]
