# Generated by Django 4.1 on 2023-06-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0013_remove_section_domain_discussion_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discussion",
            name="last_comment",
            field=models.DateTimeField(null=True),
        ),
    ]
