# Generated by Django 4.1 on 2023-07-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0025_usercontext_first_name_usercontext_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="display_fullname",
            field=models.BooleanField(default=False),
        ),
    ]
