# Generated by Django 4.1 on 2023-07-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0027_usersection_domain_alter_usersection_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSectionDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=60, null=True)),
                ("description", models.CharField(max_length=240, null=True)),
                (
                    "userSection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_section_set",
                        to="discussions.usersection",
                    ),
                ),
            ],
        ),
    ]
