# Generated by Django 4.1 on 2023-07-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0028_usersectiondomain"),
    ]

    operations = [
        migrations.RemoveField(model_name="usersection", name="domains",),
    ]
