# Generated by Django 4.1 on 2023-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0030_usercontext_about_me"),
    ]

    operations = [
        migrations.RemoveField(model_name="usercontext", name="ui_theme",),
        migrations.RemoveField(model_name="usercontext", name="user",),
        migrations.RemoveField(model_name="usersection", name="user",),
        migrations.RemoveField(model_name="usersectiondomain", name="userSection",),
        migrations.DeleteModel(name="UITheme",),
        migrations.DeleteModel(name="UserContext",),
        migrations.DeleteModel(name="UserSection",),
        migrations.DeleteModel(name="UserSectionDomain",),
    ]
