# Generated by Django 4.1 on 2023-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0034_region_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
