# Generated by Django 4.1 on 2023-08-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0037_remove_discussion_section_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="first_level_domain",
            field=models.CharField(default="www", max_length=80),
        ),
    ]
