# Generated by Django 4.1 on 2023-08-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0038_discussion_first_level_domain"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="ip_address",),
    ]
