# Generated by Django 4.1 on 2023-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0040_remove_discussion_first_level_domain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region", old_name="abb", new_name="abbrevation",
        ),
        migrations.AddField(
            model_name="section",
            name="region",
            field=models.CharField(default="cz", max_length=2),
        ),
    ]
