# Generated by Django 4.1 on 2023-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0045_alter_discussion_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="root_id", field=models.IntegerField(default=0),
        ),
    ]
