# Generated by Django 4.1 on 2023-09-04 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussions", "0046_comment_root_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="evaluator",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="favorite",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
