# Generated by Django 4.1 on 2023-06-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0002_section_tabname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="default_section",
            field=models.IntegerField(default=0),
        ),
    ]
