# Generated by Django 4.1 on 2023-06-25 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussions", "0008_discussion_section_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_of_discusses_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
