# Generated by Django 4.1 on 2023-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0010_alter_comment_evaluator"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="preffered_theme",
            field=models.IntegerField(default=0),
        ),
    ]
