# Generated by Django 4.1 on 2023-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0011_usercontext_preffered_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="articletheme",
            name="number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
