# Generated by Django 4.1 on 2023-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0012_articletheme_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="section", name="domain",),
        migrations.AddField(
            model_name="discussion",
            name="domain",
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
