# Generated by Django 4.1 on 2023-06-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0014_discussion_comment_count_discussion_last_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="last_comment",),
    ]
