# Generated by Django 4.1 on 2023-06-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0017_discussion_comments_count_discussion_last_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercontext",
            old_name="preffered_theme",
            new_name="prefered_theme",
        ),
    ]
