# Generated by Django 4.1 on 2023-06-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0018_rename_preffered_theme_usercontext_prefered_theme"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="comments_count",),
    ]
