# Generated by Django 4.1 on 2023-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0019_remove_discussion_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
