# Generated by Django 4.1 on 2023-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0020_discussion_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="replies_count",
            field=models.IntegerField(default=0),
        ),
    ]
