# Generated by Django 4.1 on 2023-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0021_comment_replies_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="prefered_section",
            field=models.IntegerField(default=0),
        ),
    ]
