# Generated by Django 4.1 on 2023-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0022_usercontext_prefered_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="displayed_username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
