# Generated by Django 4.1 on 2023-07-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0023_usercontext_displayed_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("description", models.CharField(max_length=240, null=True)),
                ("number", models.IntegerField(default=0, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("domains", models.ManyToManyField(null=True, to="discussions.domain")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_context_set",
                        to="discussions.usercontext",
                    ),
                ),
            ],
        ),
    ]
