# Generated by Django 4.1 on 2023-07-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0024_usersection"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usercontext",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usercontext",
            name="photo",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
