# Generated by Django 4.1 on 2023-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0029_remove_usersection_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="about_me",
            field=models.TextField(null=True),
        ),
    ]
