# Generated by Django 4.1 on 2023-07-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "discussions",
            "0031_remove_usercontext_ui_theme_remove_usercontext_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="topic",),
        migrations.RemoveField(model_name="section", name="tabname",),
        migrations.DeleteModel(name="Topic",),
    ]
