# Generated by Django 4.1 on 2023-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0032_remove_discussion_topic_remove_section_tabname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="scrapping",
            field=models.BooleanField(default=False),
        ),
    ]
