# Generated by Django 4.1 on 2023-07-20 00:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0033_section_scrapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abb", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("lang", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="discussions.comment",
            ),
        ),
    ]
