# Generated by Django 4.1 on 2023-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0035_alter_discussion_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="type",
            field=models.CharField(default="P", max_length=1),
        ),
    ]
