# Generated by Django 4.1 on 2023-08-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0039_remove_discussion_ip_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="first_level_domain",),
    ]
