# Generated by Django 4.1 on 2023-08-15 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussions", "0042_alter_discussion_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="favorite",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
