# Generated by Django 4.1 on 2023-08-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0043_discussion_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="theme_of_dicsussion_set",
                to="discussions.articletheme",
            ),
        ),
    ]
